### ISSUE TITLE
Snow - Adjust Symbology

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#10]
**Per Amy:** For both primary and secondary, can you match their colors for 0, 1, 2, 3 and then as below?
No work order – clear
0 – gray
1 – yellow/gold
2 – bright blue
3 – lilac
4 – green
5 – dark blue
6 and up – dark purple

ALSO – reduce the transparency some, the colors are hard to distinguish.

DOT Legend:
![image](https://cloud.githubusercontent.com/assets/5805454/5900601/08a0f9a2-a539-11e4-830e-a8901af06faa.png)

Let me know the RGB values so I can update the map service for the legend.

**Comment by jday3** [comment]
Done. Emailed the rgb values

**Comment by JMurk** [comment]
Confirmed complete.
