### ISSUE TITLE
Snow - Primary Zones 1-8 Not Rendering Properly

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#12]
**Issue:**  Primary Zones 1-8 appear to be stuck on 0 passes.  It is almost as if these are "stuck" on the symbology from the secondaries.

![image](https://cloud.githubusercontent.com/assets/5805454/5901271/21d25a82-a53f-11e4-8ea8-d78396df35b0.png)

**Resolution:** Please investigate and resolve accordingly.

**Comment by jday3** [comment]
Fixed

**Comment by JMurk** [comment]
Looks good now.  Complete.
