### ISSUE TITLE
Snow - CSR Layers 

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#15]
Point the CSR layers in the app to the following map services:

http://cityview.baltimorecity.gov/ArcGIS/rest/services/SR/SRs_live_1day/MapServer/13

http://cityview.baltimorecity.gov/ArcGIS/rest/services/SR/SRs_live_1day/MapServer/5

**Comment by jday3** [comment]
I would have to add the whole map service. is there any way for you to create a separate map service for each of those layers?

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
