### ISSUE TITLE
Snow - Primary and Secondary Border Display.

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#18]
When a user selects primary zones for the filter, the map should only display the boundaries of the primary zones.  Secondary zone boundaries should only be shown when secondary is selected in the filters.

**Comment by JMurk** [comment]
Also, knock the thickness of the boarder down a peg if you could.

**Comment by jday3** [comment]
We can't do this right now because the secondary zones are being used for displaying the colors for passes. This is not going to be a simple change

**Comment by JMurk** [comment]
OK, we will keep this open and resolve later.

**Comment by jday3** [comment]
Done. Let me know if this works how you imagined.

**Comment by JMurk** [comment]
Looks good. I would say just increase the scale limit for secondary labels slightly.

**Comment by jday3** [comment]
Done. Let me know if you think it should be increased/decreased any more

**Comment by JMurk** [comment]
Looks good to me. Closing.
