### ISSUE TITLE
Snow - Map Refresh On Apply Not Working

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#21]
**Issue:** After clicking apply to apply the filters, the map does not change.  The user has to interact with the map first for the changes to occur.  I believe this was an issue we were having before that was fixed.

**Resolution:** Please investigate and resolve accordingly.

**Comment by jday3** [comment]
For some reason the graphics layer takes a while to update so the redraw method wasn't doing anything. I put a 3 second delay between the loading of the data and the redraw so it should work.

**Comment by JMurk** [comment]
Confirmed complete.
