### ISSUE TITLE
Snow - Symbology - Areas With No Work Orders

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#23]
Per Amy:  "City likes to see a separate color (clear or white) for work orders not created yet, so a zone that does not have a work order open, would be clear.  Should be in same layer if possible. "

I would imagine that this is fairly straight forward.  Let me know if it isn't.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
