### ISSUE TITLE
Snow - Secondary Zone Labels - Not Showing Correctly

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#26]
**Issue:**  The Secondary Zone labels are broken in the production app.  The are showing up as {Label}

![image](https://cloud.githubusercontent.com/assets/5805454/6061059/2fd7c51a-ad12-11e4-88bb-14e831bda823.png)

**Resolution:** Please investigate and resolve accordingly

**Comment by jday3** [comment]
The Label field needs to be added to the data/feature service

**Comment by JMurk** [comment]
Completed.
