### ISSUE TITLE
Snow - Primary Labels

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#7]
Label the primary zones only once.  Use the Primary Zones layer to do so.

![image](https://cloud.githubusercontent.com/assets/5805454/5881238/271139e8-a30d-11e4-803c-de6c2f244bf1.png)

**Comment by jday3** [comment]
I am using the primary zones layer, but it seems like there are still some duplicates

**Comment by JMurk** [comment]
Let me ask this... Is it feasible to include the labels in the Zone_Passes map service so that users can turn them on and off as they please?  I can also add a mask to them.

**Comment by jday3** [comment]
You could add some of the labels to the zone_passes map service, but there are only primary zones so the labels wouldn't work for secondary zones.

**Comment by JMurk** [comment]
Wont Fix.
