### ISSUE TITLE
Snow - Move Point Layers Above Polygons

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#8]
Please move the point layers (Tree Down, Icy Conditions, Vehicle Locations) above the the zone polygons.  It is hard to see them.

**Comment by jday3** [comment]
After researching, I don't think we can put feature/graphic layers below map service layers. We may have to display the zone boundaries in the Zone_Passes map service to accomplish this.

**Comment by JMurk** [comment]
Won't Fix.
