### ISSUE TITLE
Snow - Map Layer -Polygons

### ISSUE THREAD

**Issue by JMurk** [JMurk/Snowblower_Issues#9]
**Issue:** Polygon symbols in the legend appear to be getting cut off:

![image](https://cloud.githubusercontent.com/assets/5805454/5900451/4d6d4e84-a537-11e4-9185-a9b4257fd1b4.png)

**Resolution:** Please investigate and update accordingly.

**Comment by jday3** [comment]
Done.

**Comment by JMurk** [comment]
Confirmed complete.
